org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

java_version=21

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)

mod_id=natures_betrayal
mod_name=Nature's Betrayal
mod_group=es.pyronixstudio.natures_betrayal
mod_license=MIT

fabric_loader_version=0.19.3
fabric_api_version=0.116.12+1.21.1
fabric_loom_version=1.16-SNAPSHOT

neoforge_mdg_version=2.0.141

utilLib=0.0.18
